### ISSUE TITLE
table registration: cornerpt missing

### ISSUE THREAD

**Issue by DRRV** [TUWien/ReadFramework#8]
the table(form) tool does ot genrate @CornetPts attributes for TableCell, which  is mandatory for the Transkribus GUI (error when uploading the pagexml into the GUI)
<CornerPts>0 1 2 3</CornerPts>

java.lang.NullPointerException
	at eu.transkribus.core.util.PointStrUtils.parseCornerPts(PointStrUtils.java:199)
	at eu.transkribus.swt_gui.factory.TrpShapeElementFactory.addCanvasShape(TrpShapeElementFactory.java:357)
	at eu.transkribus.swt_gui.factory.TrpShapeElementFactory.addAllCanvasShapes(TrpShapeElementFactory.java:384)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.loadJAXBTranscriptIntoView(TrpMainWidget.java:1916)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.reloadCurrentTranscript(TrpMainWidget.java:1820)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.reloadCurrentPage(TrpMainWidget.java:1721)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.reloadCurrentPage(TrpMainWidget.java:1689)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.jumpToPage(TrpMainWidget.java:1409)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.nextPage(TrpMainWidget.java:1455)
	at eu.transkribus.swt_gui.mainwidget.PagesPagingToolBarListener.onNextPressed(PagesPagingToolBarListener.java:31)
	at eu.transkribus.swt.pagingtoolbar.PagingToolBarListener.widgetSelected(PagingToolBarListener.java:76)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget$13.run(TrpMainWidget.java:2297)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.show(TrpMainWidget.java:2257)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.show(TrpMainWidget.java:2241)
	at eu.transkribus.swt_gui.TrpGui.main(TrpGui.java:98)

**Comment by flow79** [comment]
Fixed (cornerpts are always added) - available in the next release
